version = "3.11.5"
runner.dialect = scala213
maxColumn = 120
align.preset = more
docstrings.style = Asterisk
rewrite.rules = [RedundantParens, SortImports]

fileOverride {
  "glob:**/examples/01-*/**" { runner.dialect = scala3 }
  "glob:**/examples/02-*/**" { runner.dialect = scala3 }
  "glob:**/examples/03-*/**" { runner.dialect = scala3 }
  "glob:**/examples/09-*/**" { runner.dialect = scala3 }
  "glob:**/examples/10-*/**" { runner.dialect = scala3 }
  "glob:**/examples/11-*/**" { runner.dialect = scala3 }
  "glob:**/examples/12-*/**" { runner.dialect = scala3 }
  "glob:**/examples/13-*/**" { runner.dialect = scala3 }
  "glob:**/examples/14-*/**" { runner.dialect = scala3 }
  "glob:**/examples/15-*/**" { runner.dialect = scala3 }
  "glob:**/examples/16-*/**" { runner.dialect = scala3 }
  "glob:**/src-3/**" { runner.dialect = scala3 }
  "glob:**/*.mill" { runner.dialect = scala3 }
}
