version = "3.10.2"
runner.dialect = scala213
maxColumn = 120
align.preset = more
docstrings.style = Asterisk
rewrite.rules = [RedundantBraces, RedundantParens, SortImports]

fileOverride {
  "glob:**/src-3/**" { runner.dialect = scala3 }
  "glob:**/examples/01-*/**" { runner.dialect = scala3 }
}
